services:

  frontend:
    build: ./front-cours
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    build: ./cours-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      DATABASE_URL: mongodb+srv://molkagh02_db_user:admin123@cluster0.icghoco.mongodb.net/coursdb?retryWrites=true&w=majority&appName=Cluster0

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: